Presentation/ApartmentManagementSystem.MVC/Areas/Admin/Controllers/DairesAddController.cs
using ApartmentManagementSystem.Domain.Entities;
using ApartmentManagementSystem.MVC.Areas.Admin.Models;
using ApartmentManagementSystem.Persistance.Context;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using NToastNotify;
using Resend;

namespace ApartmentManagementSystem.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class DairesAddController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IToastNotification _toastNotification;
        private readonly ApartmentManagementSystemDbContext _context;
        private readonly IResend _resend;
        private readonly UserManager<AppUser> _userManager;

        public DairesAddController(ILogger<HomeController> logger, IToastNotification toastNotification, IResend resend, UserManager<AppUser> userManager, ApartmentManagementSystemDbContext context)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _resend = resend;
            _userManager = userManager;
            _context = context;
        }



        public IActionResult Index()
        {
            return View();
        }

        // Add Method()
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(DairesAddModel request)
        {

            if (!ModelState.IsValid)
            {

                return View();
            }

            _toastNotification.AddSuccessToastMessage("Daire bilgileri başarıyla kaydedildi.");


            Daire daire = new();

            if (request != null)
            {
                daire.daireNo = request.DaireNo;
                daire.floorNo = request.FloorNo;

                // Kullanıcıyı UserManager ile çek
                var User = await _userManager.FindByIdAsync(request.UserId);



                // User'ı başlat
                daire.user = User;

                AppUser DaireUser = new AppUser
                {
                    UserName = daire.user.UserName,
                    firstName = daire.user.firstName,
                    lastName = daire.user.lastName,
                    PhoneNumber = daire.user.PhoneNumber,
                    Email = daire.user.Email
                };

                // Subscriptions listesini başlat
                daire.subscriptions = new List<Subscription>();

                // Subscriptions'ları request.Subscriptions'tan kopyala               
                var subscription = new Subscription
                {
                    price = request.Subscriptions,
                    isPaid = false // Varsayılan değeri false olarak ayarla
                };

                daire.subscriptions.Add(subscription);

                daire.CreatedOn = DateTime.UtcNow;

                // Daire nesnesini veritabanına ekleyin
                _context.daires.Add(daire);

                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    // Hata mesajını logla
                    _logger.LogError(ex, "SaveChangesAsync hatası");
                    throw; // Hatanın tekrar fırlatılması
                }


            };

            return View();


        }
      


    }
    
    

    
}

Presentation/ApartmentManagementSystem.MVC/Controllers/DairesAddController.cs
using ApartmentManagementSystem.Domain.Entities;
using ApartmentManagementSystem.MVC.Models.Request;
using ApartmentManagementSystem.Persistance.Context;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using NToastNotify;
using Resend;

namespace ApartmentManagementSystem.MVC.Controllers
{
    
    public class DairesAddController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IToastNotification _toastNotification;
        private readonly ApartmentManagementSystemDbContext _context;
        private readonly IResend _resend;
        private readonly UserManager<AppUser> _userManager;

        public DairesAddController(ILogger<HomeController> logger, IToastNotification toastNotification, IResend resend, UserManager<AppUser> userManager, ApartmentManagementSystemDbContext context)
        {
            _logger = logger;
            _toastNotification = toastNotification;
            _resend = resend;
            _userManager = userManager;
            _context = context;
        }



        public IActionResult Index()
        {
            return View();
        }

        // Add Method()
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost] // https://localhost:7063/DairesAdd/Add
        public async Task<IActionResult> Add(DairesRequest request)
        {

            if (!ModelState.IsValid)
            {
                return View();
            }

            _toastNotification.AddSuccessToastMessage("Daire bilgileri başarıyla kaydedildi.");


            Daire daire = new();

            if (request != null)
            {
                daire.daireNo = request.DaireNo;
                daire.floorNo = request.FloorNo;

                // Kullanıcıyı UserManager ile çek
                var User = await _userManager.FindByIdAsync(request.UserId);

                // User'ı başlat
                daire.user = User;

                AppUser DaireUser = new AppUser
                {
                    UserName = daire.user.UserName,
                    firstName = daire.user.firstName, 
                    lastName = daire.user.lastName,
                    PhoneNumber = daire.user.PhoneNumber,
                    Email = daire.user.Email
                };

                // Subscriptions listesini başlat
                daire.subscriptions = new List<Subscription>();

                // Subscriptions'ları request.Subscriptions'tan kopyala               
                    var subscription = new Subscription
                    {
                        price = request.Subscriptions,
                        isPaid = false // Varsayılan değeri false olarak ayarla
                    };

                    daire.subscriptions.Add(subscription);   
                
                daire.CreatedOn = DateTime.UtcNow;

                // Daire nesnesini veritabanına ekleyin
                _context.daires.Add(daire);

                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (Exception ex)
                {
                    // Hata mesajını logla
                    _logger.LogError(ex, "SaveChangesAsync hatası");
                    throw; // Hatanın tekrar fırlatılması
                }


            }

            return View();


        }
    }
}

Presentation/ApartmentManagementSystem.MVC/Views/DairesAdd/Add.cshtml
@using ApartmentManagementSystem.MVC.Models.Request
@using ApartmentManagementSystem.MVC.Services
@await Component.InvokeAsync("NToastNotify")
@inject IToasterService toastService
@model DairesRequest
@{
    ViewData["Title"] = "Daires";
}

@section Scripts
{
    @await Html.PartialAsync("_ValidationScriptsPartial")
}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="text-center mb-4">Daire Ekleme Sayfası</h2>

            @if (TempData["SuccessMessage"] != null)
            {
                <div class="alert alert-info" role="alert">
                    @TempData["SuccessMessage"]
                    toastService.ShowSuccess("Success")
                </div>
            }

            <form asp-controller="DairesAdd" asp-action="Add" method="post">
                <div class="mb-3 row">
                    <label for="DaireNo" class="col-md-4 col-form-label">Daire No</label>
                    <div class="col-sm-8">
                        <input asp-for="DaireNo" class="form-control">
                        <span class="text-danger" asp-validation-for="DaireNo"></span>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="FloorNo" class="col-md-4 col-form-label">Kat No</label>
                    <div class="col-sm-8">
                        <input asp-for="FloorNo" class="form-control">
                        <span class="text-danger" asp-validation-for="FloorNo"></span>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="UserId" class="col-md-4 col-form-label">Kullanıcı</label>
                    <div class="col-sm-8">
                        <input asp-for="UserId" class="form-control">
                        <span class="text-danger" asp-validation-for="UserId"></span>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="Subscriptions" class="col-md-4 col-form-label">Aidat</label>
                    <div class="col-sm-8">
                        <input asp-for="Subscriptions" class="form-control">
                        <span class="text-danger" asp-validation-for="Subscriptions"></span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8 offset-md-4">
                        <button type="submit" class="btn btn-primary">Kaydet</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>