Presentation/ApartmentManagementSystem.MVC/Areas/Admin/Models/UpdateDaireViewModel.cs
namespace ApartmentManagementSystem.MVC.Areas.Admin.Models
{
    public class UpdateDaireViewModel
    {
    }
}

Presentation/ApartmentManagementSystem.MVC/Areas/Admin/Controllers/UpdateDaireController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace ApartmentManagementSystem.MVC.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class UpdateDaireController : Controller
    {
        [HttpPost]
        public IActionResult UpdateDaire()
        {
            return View();
        }
    }
}

Presentation/ApartmentManagementSystem.MVC/Areas/Admin/Views/UpdateDaire/UpdateDaire.cshtml
@using ApartmentManagementSystem.MVC.Areas.Admin.Models;
@using ApartmentManagementSystem.MVC.Models.Request;

@model DairesRequest

@{
    ViewData["Title"] = "Daire Güncelleme Sayfası";
}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <h2 class="text-center mb-4">Daire Ekleme Sayfası</h2>

            <form asp-controller="UpdateDaire" asp-action="UpdateDaire" method="post">
                <div class="mb-3 row">
                    <label for="DaireNo" class="col-md-4 col-form-label">Daire No</label>
                    <div class="col-sm-8">
                        <input asp-for="DaireNo" class="form-control">
                        <span class="text-danger" asp-validation-for="DaireNo"></span>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="FloorNo" class="col-md-4 col-form-label">Kat No</label>
                    <div class="col-sm-8">
                        <input asp-for="FloorNo" class="form-control">
                        <span class="text-danger" asp-validation-for="FloorNo"></span>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="UserId" class="col-md-4 col-form-label">Kullanıcı</label>
                    <div class="col-sm-8">
                        <input asp-for="UserId" class="form-control">
                        <span class="text-danger" asp-validation-for="UserId"></span>
                    </div>
                </div>

                <div class="mb-3 row">
                    <label for="Subscriptions" class="col-md-4 col-form-label">Aidat</label>
                    <div class="col-sm-8">
                        <input asp-for="Subscriptions" class="form-control">
                        <span class="text-danger" asp-validation-for="Subscriptions"></span>
                    </div>
                </div>

                <div class="row">
                    <div class="col-md-8 offset-md-4">
                        <button type="submit" class="btn btn-primary">Kaydet</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>